#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with >$ bundle exec jekyll serve --config _config.yml,_config_dev.yml
# To enable debug messages of the ruby gem files: >$ bundle exec jekyll serve --config _config.yml,_config_dev.yml --verbose
#
# Overriding local gem paths or repositories:
# bundle config local.GEM_NAME /path/to/local/git/repository
#
# More info on local override and git repositories in bundler:
# https://sourcediving.com/use-bundler-local-repository-override-when-developing-your-git-gems-7beeea3818c0
# https://bundler.io/guides/git.html

url: 'http://localhost:4000'
